#!/bin/bash

set -x

IP=$(ifconfig | awk '/inet/ { print $2 }' | egrep -v '^fe|^127|^192|^172|::' | head -1)
IP=${IP#addr:}

DL_SUFFIX=Linux-64bit
INNER_SUFFIX=linux_amd64
HUGO_VERSION=0.27

if [[ $HOSTNAME == "node"* ]] ; then
    #rightscale
    IP=$(grep $(hostname)_ext /etc/hosts | awk '{print $1}')
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    IP=localhost
    DL_SUFFIX=macOS-64bit
    INNER_SUFFIX=macos-64bit
fi


NOTEBOOK=GremlinConceptsWorkshop.studio-nb.tar
POST_FILE="file=@./notebooks/"$NOTEBOOK
curl -H "Accept-Encoding: gzip" -X POST -F $POST_FILE http://$IP:9091/api/v1/notebooks/import &> /dev/null

NOTEBOOK2=GremlinConceptsWorkshop___ANSWERS.studio-nb.tar
POST_FILE="file=@./notebooks/"$NOTEBOOK2
curl -H "Accept-Encoding: gzip" -X POST -F $POST_FILE http://$IP:9091/api/v1/notebooks/import &> /dev/null
